# Generated by Django 5.0.6 on 2024-05-18 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='Место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('action', models.TextField(verbose_name='Действие')),
                ('periodicity', models.IntegerField(default=1, verbose_name='Периодичность')),
                ('time_to_complete', models.TimeField(blank=True, null=True, verbose_name='Время на выполнение')),
                ('award', models.TextField(blank=True, null=True, verbose_name='Награда')),
                ('publish', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('sign_pleasant_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('last_notification', models.DateTimeField(blank=True, null=True, verbose_name='Последнее уведомление')),
                ('pleasant_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habits', verbose_name='Приятная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
