# Generated by Django 5.0.6 on 2024-05-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='place',
            field=models.CharField(max_length=150, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
    ]
